version: '2'
services:
  app:
    container_name: app-springboot-south
    image: 'app.jar'
    build: ./
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=DB_desafio2