spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/DB_desafio2
    username: postgres
    password: postgres

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/DB_desafio2
    locations:
      - classpath:db/migration