spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/Stock
    username: postgres
    password: postgres

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/Stock
    locations:
      - classpath:db/migration